'use client';
/* eslint-disable @next/next/no-img-element -- profile URLs are user-provided at runtime */

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { api } from '@/libs/api.js';
import { PrivateRoute, useAuth } from '@/libs/auth-context.js';
import { dashboardEndpoint, initials } from '@/libs/utils.js';
import { AdminPrompts, AdminReports, AdminUsers, Payments } from './AdminViews.js';
import { CreatorAnalytics, DashboardHome, Profile } from './OverviewViews.js';
import { MyReviews, OwnerPrompts, PromptForm, SavedPrompts } from './PromptViews.js';
import { Stats } from './primitives.js';

const routes = { user: [['Dashboard Home',''],['Add Prompt','add-prompt'],['My Prompts','my-prompts'],['Saved Prompts','saved-prompts'],['My Reviews','my-reviews'],['Profile','profile']], creator: [['Creator Dashboard Home',''],['Add Prompt','add-prompt'],['My Prompts','my-prompts'],['Analytics','analytics'],['Profile','profile']], admin: [['Admin Dashboard Home',''],['All Users','admin/users'],['All Prompts','admin/prompts'],['All Payments','admin/payments'],['Reported Prompts','admin/reports'],['Analytics','admin/analytics'],['Profile','profile']] };
export default function DashboardClient() { return <PrivateRoute><Dashboard /></PrivateRoute>; }

function Dashboard() { const { user } = useAuth(); const params = useParams(); const view = (params.view || []).join('/'); const [page, setPage] = useState(1); const [data, setData] = useState(null); const endpoint = view === '' && user.role === 'creator' ? '/dashboard/analytics' : view === '' && user.role === 'admin' ? '/dashboard/admin/stats' : dashboardEndpoint(view, page); const allowed = routes[user.role].some(([, path]) => path === view); const load = async () => { if (!allowed || view === 'add-prompt' || view === 'profile') return; try { setData(await api(endpoint)); } catch (error) { toast.error(error.message); setData(null); } }; useEffect(() => { if (!allowed || view === 'add-prompt' || view === 'profile') return; let active = true; api(endpoint).then((result) => { if (active) setData(result); }).catch((error) => { if (active) { toast.error(error.message); setData(null); } }); return () => { active = false; }; }, [allowed, endpoint, view]); return <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="section-label">Private dashboard route</p><h1 className="mt-3 font-display text-4xl font-black capitalize sm:text-5xl">{user.role} Dashboard</h1><div className="hard-card mt-8 overflow-hidden rounded-[2rem]"><div className="grid lg:grid-cols-[280px_1fr]"><Sidebar user={user} view={view} /><div className="min-w-0 p-5 sm:p-7">{!allowed ? <Forbidden /> : view === 'add-prompt' ? <PromptForm onSaved={load} /> : view === 'profile' ? <Profile /> : !data ? <div className="skeleton h-64 rounded-3xl" /> : <View view={view} data={data} load={load} user={user} page={page} setPage={setPage} />}</div></div></div></div></section>; }

function Sidebar({ user, view }) { return <aside className="border-b border-[var(--line)] p-5 lg:border-b-0 lg:border-r"><div className="soft-card mb-5 flex items-center gap-3 rounded-3xl p-4"><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-violet-500 to-pink-500 font-black text-white">{user.photoURL ? <img alt="" src={user.photoURL} className="h-full w-full object-cover" /> : initials(user.name)}</div><div><b>{user.name}</b><p className="text-xs capitalize muted">{user.subscription} · {user.role}</p></div></div><nav className="grid gap-2 text-sm font-extrabold">{routes[user.role].map(([label, path]) => <Link key={label} href={`/dashboard/${path}`} className={`rounded-2xl px-4 py-3 ${view === path ? 'bg-[var(--lime)] text-slate-950' : 'hover:bg-white/10'}`}>{label}</Link>)}</nav></aside>; }
function View({ view, data, load, user, page, setPage }) { if (!view) return <DashboardHome data={data} />; if (view === 'analytics') return <CreatorAnalytics data={data} />; if (view === 'my-prompts') return <OwnerPrompts prompts={data.prompts} load={load} />; if (view === 'saved-prompts') return <SavedPrompts bookmarks={data.bookmarks} load={load} />; if (view === 'my-reviews') return <MyReviews reviews={data.reviews} />; if (view === 'admin/users') return <AdminUsers users={data.users} currentUser={user} load={load} />; if (view === 'admin/prompts') return <AdminPrompts data={data} load={load} page={page} setPage={setPage} />; if (view === 'admin/payments') return <Payments payments={data.payments} />; if (view === 'admin/reports') return <AdminReports reports={data.reports} load={load} />; if (view === 'admin/analytics') return <Stats items={Object.entries(data)} />; return <Forbidden />; }
function Forbidden() { return <div className="soft-card rounded-3xl p-6"><h2 className="font-display text-2xl font-black">Route unavailable</h2><p className="mt-2 muted">This dashboard route is not available for your account role.</p></div>; }
